server:
  port: 8085

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR

spring:
  datasource:
    url: jdbc:h2:file:./db/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
